
CREATE TABLE IF NOT EXISTS M_SCHOOL (
  MS_CD CHAR(6) NOT NULL,
  MS_CREATE_DATETIME DATETIME DEFAULT NULL,
  MS_CREATE_MSU_ID INT DEFAULT NULL,
  MS_UPDATE_DATETIME DATETIME DEFAULT NULL,
  MS_UPDATE_MSU_ID INT DEFAULT NULL,
  MS_DELETE_DATETIME DATETIME DEFAULT NULL,
  MS_NAME VARCHAR(50) DEFAULT NULL,
  MS_NAME_ENG VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (MS_CD)
);