
CREATE TABLE IF NOT EXISTS M_SCHOOL_SCHEDULE_CLOSED (
  MSSC_ID INT NOT NULL AUTO_INCREMENT,
  MSSC_CREATE_DATETIME DATETIME NOT NULL,
  MSSC_CREATE_MSU_ID INT NOT NULL,
  MSSC_UPDATE_DATETIME DATETIME NOT NULL,
  MSSC_UPDATE_MSU_ID INT NOT NULL,
  MSSC_DELETE_DATETIME DATETIME DEFAULT NULL,
  MSSC_CLOSED_DATE DATE NOT NULL,
  PRIMARY KEY (MSSC_ID)
);