

CREATE TABLE IF NOT EXISTS M_COURSE_SMALL (
  MCS_CD CHAR(5) NOT NULL,
  MCS_CREATE_DATETIME DATETIME NOT NULL,
  MCS_CREATE_MSU_ID INT NOT NULL,
  MCS_UPDATE_DATETIME DATETIME NOT NULL,
  MCS_UPDATE_MSU_ID INT NOT NULL,
  MCS_DELETE_DATETIME DATETIME DEFAULT NULL,
  MCS_MCM_CD CHAR(3) NOT NULL,
  MCS_NAME VARCHAR(40) NOT NULL,
  MCS_SORT INT NOT NULL,
  PRIMARY KEY (MCS_CD)
);