CREATE TABLE IF NOT EXISTS M_COURSE_LARGE (
  MCL_CD CHAR(1) NOT NULL,
  MCL_CREATE_DATETIME DATETIME NOT NULL,
  MCL_CREATE_MSU_ID INT NOT NULL,
  MCL_UPDATE_DATETIME DATETIME NOT NULL,
  MCL_UPDATE_MSU_ID INT NOT NULL,
  MCL_DELETE_DATETIME DATETIME DEFAULT NULL,
  MCL_NAME VARCHAR(40) NOT NULL,
  MCL_SORT INT NOT NULL,
  PRIMARY KEY (MCL_CD)
);